### PR TITLE
feat: add return_embeddings parameter to storage executors

### PR DESCRIPTION
**Pull request by alaeddine-13**
closes https://github.com/jina-ai/internal-tasks/issues/135

### CODE REVIEW

**Comment by cristianmtr** [comment]
Looks good, but can u add a test to show that it doesn't override your embeddings?

Just copy-paste it across the three storage indexers

**Review by cristianmtr — CHANGES_REQUESTED** [review]
add a test

**Comment by alaeddine-13** [comment]
> Looks good, but can u add a test to show that it doesn't override your embeddings?
> 
> Just copy-paste it across the three storage indexers

I added the tests

**Review by cristianmtr — APPROVED** [review]
looks good!

**Pull request merged**
