### PR TITLE
fix(MongoDBStorage): fix embedding datatype to float

### PR DESCRIPTION
**Pull request by sauravgarg540**
This PR changes embedding to a list of python float from list of NumPy float

### CODE REVIEW

**Comment by cristianmtr** [comment]
Can you rebase, in order to fix the failing `gpu-tests`?

**Comment by sauravgarg540** [comment]
Hello @cristianmtr, I have rebased the branch and all the checks have been passed. 😄

**Comment by cristianmtr** [comment]
Thank you for your contribution!

**Review by cristianmtr — APPROVED** [review]

**Comment by cristianmtr** [comment]
FYI You can get swag for your contribution. Check our blog post on it [here](https://jina.ai/blog/swag/) or join our [slack](https://slack.jina.ai/) and check in `#swag` channel

**Pull request merged**
