### PR TITLE
chore: delete two executors that have already been separated

### PR DESCRIPTION
**Pull request by Hippopotamus0308**
Goals:

- ...
- ...

- [ ] Bumped version (in README of Executor)

PR feedback: @jina-ai/workstream-hub

### CODE REVIEW

**Review by cristianmtr — DISMISSED** [review]

**Review by cristianmtr — APPROVED** [review]
Why did you delete both vgg audio and CLIP in one PR? Was that intentional, or did you mean to split it into 2 PRs perhaps?

**Comment by Hippopotamus0308** [comment]
> Why did you delete both vgg audio and CLIP in one PR? Was that intentional, or did you mean to split it into 2 PRs perhaps?

I was about to delete the both, sorry that I misnamed this pr.

**Comment by cristianmtr** [comment]
> > Why did you delete both vgg audio and CLIP in one PR? Was that intentional, or did you mean to split it into 2 PRs perhaps?
> 
> I was about to delete the both, sorry that I misnamed this pr.

Np. Merge it now then?

**Comment by Hippopotamus0308** [comment]
> > > Why did you delete both vgg audio and CLIP in one PR? Was that intentional, or did you mean to split it into 2 PRs perhaps?
> > 
> > 
> > I was about to delete the both, sorry that I misnamed this pr.
> 
> Np. Merge it now then?

Yes, thanks.

**Pull request merged**
