### PR TITLE
fix: numpy searcher docs traversal

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
the NumpySearcher used to add matches to the root level, but it should add them into the corresponding traversal level, then will be helpful for ranker to rerank

### CODE REVIEW

**Comment by tadejsv** [comment]
I'm fine with this - can you add some tests?

**Comment by Yongxuanzhang** [comment]
> I'm fine with this - can you add some tests?

ah yes. We need tests

**Review by cristianmtr — APPROVED** [review]

**Comment by Yongxuanzhang** [comment]
> > I'm fine with this - can you add some tests?
> 
> ah yes. We need tests, will add soon

**Review by tadejsv — APPROVED** [review]
LGTM

**Pull request merged**
