### PR TITLE
fix: psql import

### PR DESCRIPTION
**Pull request by cristianmtr**
- revert PSQL init

### CODE REVIEW

**Review by tadejsv — CHANGES_REQUESTED** [review]
If you are attaching change to CI to this PR, then we should do it properly and implement the change that does not require this reversion of the previous PR, see here https://github.com/jina-ai/executors/issues/61#issuecomment-895203429

**Comment by cristianmtr** [comment]
I'll revert the CI from this PR

**Comment by tadejsv** [comment]
I think to get the tests to work you need to put things back into `__init__.py`. With changing the CI I was just refering to addition of Docker testing (which I think is a great idea, just better suited for a separate PR, if we want this as a quickfix). 

For the error we were getting we don't actually need Docker to reproduce, this will be enough (I think?)
```python
def test_config():
    ex = BaseExecutor.load_config("../../config.yml")
```

**Review by tadejsv — APPROVED** [review]
Ok, if you tested locally (with docker) and it works, let's merge

**Pull request merged**
