### PR TITLE
fix: use python 3.8 in CI

### PR DESCRIPTION
**Pull request by alaeddine-13**
Executor normalizer needs python 3.8 (needs recent AST library)
closes https://github.com/jina-ai/executors/pull/178

### CODE REVIEW

**Review by tadejsv — CHANGES_REQUESTED** [review]
We should use a container

**Comment by alaeddine-13** [comment]
> We should use a container

can you re-check ?

**Comment by tadejsv** [comment]
Ok then change looks good (you might consider setting `--user` for the container), and we need to then remove previous pip installation of the normalizer. Also, we need to test it somewhere (best place would be the normalizer repo)

**Comment by cristianmtr** [comment]
For any CI/CD changes we need to test that all Executors still work.

1. Can you do a mock change in all the folders so that they are all triggered?
2. Can you enable the `jina hub push` job (see `cd.yml`) to run in the PR?

**Review by cristianmtr — DISMISSED** [review]
See comment above

**Comment by tadejsv** [comment]
@cristianmtr This is something that will take a lot of time, speaking from experience

**Comment by cristianmtr** [comment]
> @cristianmtr This is something that will take a lot of time, speaking from experience

Fixing it afterwards also takes a lot of time.

**Comment by tadejsv** [comment]
Let me create a quickfix then. The problem is that the progress on other PRs is blocked currently, because unit tests do not work due to new version of executor-normalizer

**Comment by alaeddine-13** [comment]
dummy changes made and tested some of the executors
And then the changes are reverted

**Review by tadejsv — APPROVED** [review]
LGTM!

**Pull request merged**
