### PR TITLE
docs: update version

### PR DESCRIPTION
**Pull request by Hippopotamus0308**
Goals:

- ...
- ...

- [ ] Bumped version (in README of Executor)

PR feedback: @jina-ai/workstream-hub

### CODE REVIEW

**Comment by cristianmtr** [comment]
regarding

> I didn't update the customImageTorchEncoder and TFIDFTextEncoder as it import 'PretrainedModelFileDoesNotExist' from 'jina.excepts' which the latest jina version doesn't support and fail to pass the unit test, while other executors are ok

Sounds like a custom Exception. Just redeclare it

**Comment by cristianmtr** [comment]
Missing

- `jinahub/encoders/image/CLIPImageEncoder/clip_image.py`
- `jinahub/encoders/text/LaserEncoder/laser_encoder.py`

**Comment by cristianmtr** [comment]
unit tests and gpu tests of Laser failing

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Pull request merged**
