### PR TITLE
docs: fix Simple README

### PR DESCRIPTION
**Pull request by cristianmtr**

### CODE REVIEW

**Comment by tadejsv** [comment]
What is this bug?

**Comment by cristianmtr** [comment]
It wasn't a bug. It had something to do with the workspace not being saved at container shutdown, when using it with `jinahub+docker`.

**Comment by tadejsv** [comment]
Okay. And is there any fix that can be done for that? Since SimpleIndexer will probably be one of the most used executors, we should enable its use in a Docker container

**Comment by cristianmtr** [comment]
Again, not sure it was an actual bug.

This works

```python
import numpy as np

from jina import Flow, Document

f = Flow().add(
    uses='jinahub+docker://SimpleIndexer',
    uses_with={'index_file_name': 'name'},
    uses_metas={'workspace': '/inner_workspace'},
    volumes=['workspace:/inner_workspace']
)

with f:
    resp = f.post(
        on='/index',
        inputs=[Document(id='a', embedding=np.array([1]))],
        return_results=True,
    )

with f:
    resp = f.post(
        on='/search',
        inputs=[Document(embedding=np.array([1]))],
        return_results=True,
        parameters={'top_k': 5},
    )
    assert resp[0].docs[0].matches[0].id == 'a'
```

**Comment by tadejsv** [comment]
Okay, we should then also have a ticket to fix this issue

**Comment by cristianmtr** [comment]
> Okay, we should then also have a ticket to fix this issue

What issue? It works. Might have been fixed in the meantime, if it was a problem

**Comment by tadejsv** [comment]
Ah my bad, I thought you were adding the warning.

**Review by tadejsv — APPROVED** [review]

**Pull request merged**
