### PR TITLE
fix: empty push

### PR DESCRIPTION
**Pull request by cristianmtr**
Fix pushing an empty Executor

### CODE REVIEW

**Comment by tadejsv** [comment]
How does an empty executor directory even make it to the `needs.prep-push-bed.outputs.matrix` ?

**Comment by cristianmtr** [comment]
> How does an empty executor directory even make it to the `prep-push-bed.outputs.matrix` ?

It's because of this line https://github.com/jina-ai/executors/blob/11a488acb56865f96a7816d2d9b915a5ff0c2041/scripts/get-all-test-paths.sh#L30

If it's an empty array, it prints an empty string

**Comment by tadejsv** [comment]
Ok, so if I understand correctly, this happens when in fact no executors have been changed (e.g. if only the directory's readme is updated)?

**Comment by cristianmtr** [comment]
> Ok, so if I understand correctly, this happens when in fact no executors have been changed (e.g. if only the directory's readme is updated)?

Yes, or other non-executor files

**Review by tadejsv — APPROVED** [review]
LGTM!

**Pull request merged**
